### ISSUE TITLE
Toonkit > Animation > Import Anim

### ISSUE THREAD

**Issue by BorisToonkit** [CyrilToonkit/Toonkit_Module_Base#17]
[Erreur Import Anim (None, pas considéré correctement) ](https://github.com/CyrilToonkit/Toonkit_Module_Base/blob/master/Maya/scripts/tkMenu/_20_Animation/_300_ImportAnim.py#L16)

Ajouter : 
        if len(namespace) == 0:
            namespace = None

**Comment by CyrilToonkit** [comment]
As it's an open source project we have to try to contribute in english, sorry 😊.
