### ISSUE TITLE
TkMayaCore

### ISSUE THREAD

**Issue by BorisToonkit** [CyrilToonkit/Toonkit_Module_Base#18]
[Erreur Delete History](https://github.com/CyrilToonkit/Toonkit_Module_Base/blob/c7046befd57607da2970517e18401e1a4cdb741a/Maya/scripts/tkMayaCore.py#L2798)

Ajouter : 
    pc.select(inObject)

**Comment by CyrilToonkit** [comment]
As it's an open source project we have to try to contribute in english, sorry 😊
